import type { Metadata } from "next";
import localFont from "next/font/local";
import { Box } from "@mui/material";
import ThemeRegistry from "./components/ThemeRegistry";

// Sora font for headers - variable font
const sora = localFont({
  src: "../../public/fonts/Sora-VariableFont_wght.ttf",
  variable: "--font-sora",
  fallback: ["sans-serif"],
  display: "swap",
});

// Inter font for text - variable font
const inter = localFont({
  src: [
    {
      path: "../../public/fonts/Inter-VariableFont_opsz,wght.ttf",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../../public/fonts/Inter-Italic-VariableFont_opsz,wght.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-inter",
  fallback: ["sans-serif"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/rhodes-hub-logo-dark.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ margin: 0, padding: 0 }}>
      <body className={`${sora.variable} ${inter.variable}`} style={{ margin: 0, padding: 0 }}>
        <ThemeRegistry>
          <Box
            sx={{
              pt: "64px",
              minHeight: "calc(100vh - 64px)",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <Box sx={{ flex: 1 }}>{children}</Box>
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
